apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store-gateway
  namespace: monitoring
  labels:
    app: thanos
    component: store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos
      component: store
  template:
    metadata:
      labels:
        app: thanos
        component: store
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: thanos
          image: quay.io/thanos/thanos:v0.32.2
          args:
            - "store"
            - "--grpc-address=0.0.0.0:10901"
            - "--objstore.config=$(:OBJSTORE_CONFIG)"
          env:
            - name: OBJSTORE_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: thanos-s3-config
                  key: config
          ports:
            - containerPort: 10901
              name: grpc
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
  namespace: monitoring
  labels:
    app: thanos
    component: store
spec:
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
  selector:
    app: thanos
    component: store
  type: ClusterIP
